### ISSUE TITLE
BUG: editor.runCommand is not a function

### ISSUE THREAD

**Issue by baoc75** [GrapesJS/studio#11]
### What browser are you using?

Chrome v131

### Describe the bug

**How to reproduce the bug?**
Try running editor.runCommand() after the editor has been initialized throw error. 

**What is the expected behavior?**
I should able to run the command

**What is the current behavior?**
It throws `Uncaught TypeError: editor.runCommand is not a function`

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
 const editor = createStudioEditor({
   //initialize
});

editor.runCommand('get-tailwindCss', {
     callback: (twcss) => {
           // some code here
    }
});
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
`createStudioEditor` doesn't return the editor. 
I recommend adding a plugin to start interacting with the editor instance.
```js
createStudioEditor({
  // ...
  plugins: [
    // your plugin here
    (editor) => {
      editor.runCommand(...)
    }
  ]
}) 
```
